name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npx prettier --check .
      - run: npx eslint .
      - run: npx svelte-check
      - run: bash scripts/validate-json-schema.bash

  docker:
    needs: linting
    uses: samply/github-workflows/.github/workflows/docker-ci.yml@main
    with:
      image-name: "samply/dhki-explorer"
      #push-to: auto
      #build-context: '.'
      #build-file: './Dockerfile'
      #build-platforms: "linux/amd64"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
