name: Linting
on:
    push:
    pull_request:

jobs:
    verify-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - run: npm ci
            - run: npx prettier --check .
            - run: npx eslint .
            - run: npm run check
            - run: npm run build
            - run: bash scripts/validate-json-schema.bash
